import type { Metadata } from "next";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
//relative path imports
import MainLayout from "@/layouts";
import { LoadingProvider } from "@/context/LoadingContext";
import LoadingOverlay from "@/components/LoadingOverlay";

export const metadata: Metadata = {
  title: "Zorbee Super Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <LoadingProvider>
            <MainLayout>{children}</MainLayout>
            <LoadingOverlay />
          </LoadingProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
